spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.245.130:3306/shoe_factory_assistant_dev?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456

app:
  file-storage:
    root-path: D:/清化资料
    libre-office-command: soffice
    libre-office-timeout-seconds: 120
