spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.40.128:3306/shoe_factory_assistant
    username: root
    password: 1234

app:
  file-storage:
    order-archive-root-path: D:/清化资料
    order-archive-customer: 达维
    order-image-archive-root-path: D:/清化资料/image
    pdf-archive-root-path: D:/清化资料/pdf
    print-image-swap-path: D:/清化资料/image/swap
    libre-office-command: soffice
    libre-office-timeout-seconds: 120