server:
  port: 8080

spring:
  application:
    name: shoe-factory-assistant
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 120MB
  profiles:
    active: @spring.profiles.active@

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto

app:
  file-storage:
    root-path: ${user.home}/shoe-factory-assistant/files
