server:
  port: 8080

spring:
  application:
    name: shoe-factory-assistant
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 120MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.75.130:3316/shoe_factory_assistant?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto

app:
  file-storage:
    root-path: ${user.home}/shoe-factory-assistant/files
    order-archive-root-path: D:/清化资料
    order-archive-customer: 达维
    order-image-archive-root-path: D:/清化资料/image
    pdf-archive-root-path: D:/清化资料/pdf
    print-image-swap-path: D:/清化资料/image/swap
    libre-office-command: soffice
    libre-office-timeout-seconds: 120
    preview-url-prefix: /api/print-previews
