spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.10.62:3306/shoe_factory_assistant_prod?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456

app:
  file-storage:
    root-path: /data/shoe-factory-assistant/files
    libre-office-command: soffice
    libre-office-timeout-seconds: 120
